# Generated by Django 5.0.1 on 2024-06-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('SCRATCH_AUTH', 'Scratch Auth'), ('USERNAME_PASSWORD', 'Password')], default='SCRATCH_AUTH', max_length=200),
            preserve_default=False,
        ),
    ]
