# Generated by Django 5.0.6 on 2024-06-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('SA', 'Scratch Auth'), ('PA', 'Password')], max_length=200),
        ),
    ]
